name: tick_tok_bio
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore:
  google_maps_flutter:
  flutter_polyline_points:
  location:
  gpx:
  convert: ^2.1.1
  firebase_storage:
  path_provider:
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  geolocator: ^5.3.2+2
  flutter_spinkit: ^4.1.2+1
  date_format: ^1.0.8
  weather: ^1.1.1
  audioplayers: ^0.15.1
  flutter_map:
  latlong: ^0.6.1

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/sounds/bell.mp3
    - assets/sounds/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf






